org: testdevelopment
app: ct-bot
service: ct-bot

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    DISCORD_TOKEN: ${param:discord_token}

functions:
  hello:
    handler: handler.hello
    url: true

plugins:
  - serverless-offline
